# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - tw.md

footer: 'contact us at <a href="mailto:info@hchy.tw">info@hchy.tw</a>'
